# Generated by Django 2.2.7 on 2019-12-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('user_id', models.IntegerField()),
                ('mb_cluster', models.FloatField()),
                ('db_cluster', models.FloatField()),
                ('cluster', models.FloatField()),
            ],
        ),
    ]
