# Generated by Django 2.2.7 on 2019-12-26 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='text',
            field=models.TextField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='data',
            name='timeStamp',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
