# Generated by Django 2.2.7 on 2019-12-27 16:14

import Caching.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caching', '0005_remove_data_popularity'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='popularity',
            field=models.IntegerField(default=Caching.models.random_value),
        ),
    ]
