# Generated by Django 2.2.7 on 2019-12-27 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Caching', '0006_data_popularity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='popularity',
        ),
    ]
