# Generated by Django 2.2.7 on 2019-12-27 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Caching', '0008_data_popularity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='popularity',
            field=models.IntegerField(default=0),
        ),
    ]
